### ISSUE TITLE
Default content doesn't work

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/forgot_password#25]
Default content doesn't work until change a bit and save something new.

Steps to reproduce:

1. Open a new Skygear account
2. Enable Welcome Email under User Auth
3. Click "Send Test Email"
4. An empty email will be sent to the mailbox designated.

Expected result:

The email shouldn't be empty, but show the correct content.

**Comment by carmenlau** [comment]
Tried in staging and production portal, cannot reproduce the problem.

**Comment by chpapa** [comment]
Okay I just tried again, can't reproduce the problem too, but #26 is still here.
