### ISSUE TITLE
pyzmail sender expect a tuple but forgot_password plugins use a plain text  environment variable

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/forgot_password#34]
The pyzmail plugins expect a tuple in the sender, like `(u'Me', 'me@foo.com')` (Ref: http://www.magiksys.net/pyzmail/api/index.html), but this plugins pass a string.

It was discovered by a user on slack, and break the feature in his case.
https://skygear.slack.com/archives/C1AD5Q51R/p1520478118000294?thread_ts=1519674866.000647&cid=C1AD5Q51R

I think we should fix:
1. Not just sender, but probably reply-to and to email might have similar problem? Need to check.
1. The environment variable, for example `FORGOT_PASSWORD_SENDER` is only an email, it wasn't specific on how we can add a sender name... We probably need another environment var like `FORGOT_PASSWORD_SENDER_NAME` too.
1. On Skygear Portal, we don't have way to specific the sender name besides email address, need an update too

**Comment by carmenlau** [comment]
Remarks: Need update plugin and portal

**Comment by carmenlau** [comment]
We will use `FORGOT_PASSWORD_SENDER` in different format

Supported formats:

* `SenderName` (email will default to no-reply@skygeario.com)
* `email@example.com` (sender name is also email@example.com)
* `SenderName <email@example.com>`
